import type { Metadata } from "next";
import "./globals.css";
import StateProvider from "@/Store/StateProvider";

export const metadata: Metadata = {
  title: "Turbo Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StateProvider>


        <html lang="en  ">
        <body>
          {children}
        </body>
      </html>
      </StateProvider>
  );
}
